### ISSUE TITLE
to_netcdf_throttled fails with newer xarray version.

### ISSUE THREAD

**Issue by HoWol76** [ScottWales/climtas#32]
Since the latest update to the stable conda module, we got two errors with climtas storing files, here's one:

```
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.04/bin/era5grib", line 10, in <module>
    sys.exit(main())
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/era5grib/era5grib.py", line 341, in main
    func(**dargs)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/era5grib/era5grib.py", line 177, in era5grib_wrf
    save_grib(ds, output, format=format)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/era5grib/era5grib.py", line 55, in save_grib
    climtas.io.to_netcdf_throttled(ds, tmp_compressed)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/climtas/io.py", line 89, in to_netcdf_throttled
    f = ds.to_netcdf(str(path), encoding=encoding, compute=False)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/core/dataset.py", line 1901, in to_netcdf
    return to_netcdf(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/api.py", line 1072, in to_netcdf
    dump_to_store(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/api.py", line 1119, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/common.py", line 265, in store
    self.set_variables(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/common.py", line 303, in set_variables
    target, source = self.prepare_variable(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 481, in prepare_variable
    encoding = _extract_nc4_variable_encoding(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.04/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 277, in _extract_nc4_variable_encoding
    raise ValueError(
ValueError: unexpected encoding parameters for 'netCDF4' backend: ['szip', 'zstd', 'bzip2', 'blosc']. Valid encodings are: {'fletcher32', 'chunksizes', 'complevel', 'least_significant_digit', 'shuffle', 'contiguous', 'zlib', '_FillValue', 'dtype'}
```

**Comment by ScottWales** [comment]
The output encoding gets set at https://github.com/ScottWales/climtas/blob/master/src/climtas/io.py#L32.

None of the keys `['szip', 'zstd', 'bzip2', 'blosc']` are added though - are they perhaps present in the input file? Do you have a minimal example showing the error?
